id,module_number,device_type,subject,step1,step2,step3,step4,recap
1,Module 1,Desktop,Introduction,Step 1,Step 2,Step 3,Step 4,Recap
2,windows,Introduction,"Welcome to Windows module of Mouse Mastery. In this section you will learn how to navigate the settings, create and save files, access the internet on your computer.",n/a,n/a,n/a,n/a,n/a
4,0001,windows,Desktop,The Desktop is the main screen that you see when you turn on your computer. You can also right-click on the desktop to access different settings.,n/a,n/a,n/a,n/a
5,0001,windows,Desktop,Right click on your desktop.,"You can arrange your desktop just like you would a physical desktop. Select ""New"" and then ""Folder"" to create a new folder on the desktop.",Type a name for the folder and press Enter. You have just created a folder and saved it on your desktop.,,"In this exercise, we explored the Desktop on our Windows computer. The Desktop is the main screen that we see when we start our computer. We learned that we can right-click on the desktop to access different settings. We created a folder and saved it on our desktop."
7,0001,windows,Taskbar,Find a program that is currently open on Taskbar and click on it.,The program will open and show up on the screen. You can start using the program immediately,Look at the pictures on the Taskbar and the words on the Desktop. See how the words on the Desktop tell you the names of the programs.,On the Taskbar click on the same icon for the program you just opened. It will disappear. Click it again and it will re-appear. This is known as minimize or maximize,In this exercise we learned about the Taskbar in Windows. The Taskbar is a long bar located at the bottom of the screen that has icons for open or pinned programs. We reopened a program that was open and it re-appeared on the screen to allow us to use it. We learned the Taskbar uses pictures for icons while the Desktop provides the name and pictures of icons.
8,0002,windows,File Explorer,File Explorer is how you find and open files. It is like a filing cabinet where you can find and open different types of files.,It is a folder icon on the Taskbar.,n/a,n/a,n/a
9,0002,windows,File Explorer,"Click on your ""File Explorer"" folder icon","A window will open up showing different files and folders on your computer. Double-click on the ""Documents"" folder to open it.","You may find documents, spreadsheets, or presentations. Try opening one of the files by double-clicking on it.","Try navigating to other folders like ""Pictures"" or ""Music"" to see what files are stored there.","In this exercise, you learned about File Explorer, which is like a filing cabinet for your computer files. File Explorer makes it easy to find and open your files on the computer. By clicking on the folder icon on the Taskbar, you opened a window with different files and folders. You explored the Documents folder and practiced opening files by double-clicking on them. You can also check out other folders like Pictures or Music to see what files are there."
10,0002,windows,Settings,"In Windows, a ""setting"" is a way to change how your computer works. For example, you can change the color of your desktop background or adjust the volume of your speakers.",n/a,n/a,n/a,n/a
